version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: fulexo_test
      POSTGRES_USER: fulexo_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:7
    command: ["valkey-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - valkeydata_test:/data

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: test_access_key
      MINIO_ROOT_PASSWORD: test_secret_key
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata_test:/data

volumes:
  pgdata_test:
  valkeydata_test:
  miniodata_test: