global:
  scrape_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
rule_files:
  - /etc/prometheus/alerts.yml
scrape_configs:
  - job_name: api
    static_configs:
      - targets: ["api:3000"]
  - job_name: worker
    static_configs:
      - targets: ["worker:3001"]