global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'fulexo-production'
    environment: 'production'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  - job_name: 'api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 10s

  - job_name: 'worker'
    static_configs:
      - targets: ['worker:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 10s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 15s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    scrape_interval: 15s

  - job_name: 'redis'
    static_configs:
      - targets: ['valkey:9121']
    scrape_interval: 15s

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 15s