#!/bin/bash
LOG_FILE="/var/log/git-auto-sync.log"
BACKUP_DIR="/opt/fulexo/server-configs"

cd /opt/fulexo

echo "$(date): Auto-sync başlatıldı" >> $LOG_FILE

# Güncel sistem bilgilerini güncelle
echo "Sistem bilgileri güncelleniyor..." >> $LOG_FILE

# Database backup
cd /opt/fulexo/compose
docker compose --env-file /etc/fulexo/fulexo.env exec postgres pg_dump -U fulexo_user fulexo > ../server-configs/databases/fulexo-db-backup-$(date +%Y%m%d-%H%M).sql 2>/dev/null
cd /opt/fulexo

# Sistem durumunu güncelle
uname -a > server-configs/system-info.txt
df -h >> server-configs/system-info.txt
free -h >> server-configs/system-info.txt
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" > server-configs/docker-status.txt

# Git değişikliklerini kontrol et
if [[ -n $(git status --porcelain) ]]; then
    echo "$(date): Değişiklikler tespit edildi, senkronizasyon başlatılıyor..." >> $LOG_FILE
    
    git add .
    git commit -m "🤖 Auto-sync: $(date '+%Y-%m-%d %H:%M:%S')

- Updated system info and docker status
- Database backup: $(date '+%Y%m%d-%H%M')
- Auto-generated by cron job"

    git push origin main
    
    if [ $? -eq 0 ]; then
        echo "$(date): Senkronizasyon tamamlandı ✅" >> $LOG_FILE
    else
        echo "$(date): Senkronizasyon hatası ❌" >> $LOG_FILE
    fi
else
    echo "$(date): Değişiklik yok, senkronizasyon atlandı" >> $LOG_FILE
fi

# Eski backup'ları temizle (7 günden eski)
find server-configs/databases/ -name "*.sql" -mtime +7 -delete 2>/dev/null

echo "$(date): Auto-sync tamamlandı" >> $LOG_FILE
