#!/bin/bash
LOG_FILE="/var/log/git-auto-sync.log"
BACKUP_DIR="/opt/fulexo/server-configs"

cd /opt/fulexo

echo "$(date): Auto-sync başlatıldı (İki yönlü)" >> $LOG_FILE

# ÖNCE GitHub'dan güncellemeleri çek
echo "$(date): GitHub'dan güncellemeler kontrol ediliyor..." >> $LOG_FILE
git fetch origin main

# Remote'da değişiklik var mı kontrol et
LOCAL=$(git rev-parse HEAD)
REMOTE=$(git rev-parse origin/main)

if [ "$LOCAL" != "$REMOTE" ]; then
    echo "$(date): GitHub'da yeni değişiklikler bulundu, çekiliyor..." >> $LOG_FILE
    git pull origin main
    
    # Docker servislerini yeniden başlat (eğer Docker dosyaları değiştiyse)
    if git diff --name-only HEAD~1 | grep -q "compose\|Dockerfile"; then
        echo "$(date): Docker dosyaları değişti, servisler yeniden başlatılıyor..." >> $LOG_FILE
        cd /opt/fulexo/compose
        docker compose --env-file /etc/fulexo/fulexo.env up -d --build 2>/dev/null
        cd /opt/fulexo
        echo "$(date): Docker servisleri güncellendi" >> $LOG_FILE
    fi
else
    echo "$(date): GitHub'da yeni değişiklik yok" >> $LOG_FILE
fi

# Güncel sistem bilgilerini güncelle
echo "$(date): Sistem bilgileri güncelleniyor..." >> $LOG_FILE

# Database backup
cd /opt/fulexo/compose
docker compose --env-file /etc/fulexo/fulexo.env exec postgres pg_dump -U fulexo_user fulexo > ../server-configs/databases/fulexo-db-backup-$(date +%Y%m%d-%H%M).sql 2>/dev/null
cd /opt/fulexo

# Sistem durumunu güncelle
uname -a > server-configs/system-info.txt
df -h >> server-configs/system-info.txt
free -h >> server-configs/system-info.txt
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" > server-configs/docker-status.txt

# SONRA local değişiklikleri push et
if [[ -n $(git status --porcelain) ]]; then
    echo "$(date): Local değişiklikler tespit edildi, GitHub'a gönderiliyor..." >> $LOG_FILE
    
    git add .
    git commit -m "🤖 Auto-sync: $(date '+%Y-%m-%d %H:%M:%S')

- Updated system info and docker status
- Database backup: $(date '+%Y%m%d-%H%M')
- Auto-generated by cron job"

    git push origin main
    
    if [ $? -eq 0 ]; then
        echo "$(date): Local değişiklikler GitHub'a gönderildi ✅" >> $LOG_FILE
    else
        echo "$(date): GitHub push hatası ❌" >> $LOG_FILE
    fi
else
    echo "$(date): Local değişiklik yok" >> $LOG_FILE
fi

# Eski backup'ları temizle (7 günden eski)
find server-configs/databases/ -name "*.sql" -mtime +7 -delete 2>/dev/null

echo "$(date): İki yönlü auto-sync tamamlandı" >> $LOG_FILE
echo "----------------------------------------" >> $LOG_FILE
