name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci --prefix apps/api || npm i --prefix apps/api
      - run: npm ci --prefix apps/web || npm i --prefix apps/web
      - run: npm run build --prefix apps/api || echo "api build"
      - run: npm run build --prefix apps/web || echo "web build"