name: Code Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        npm run install:all
    
    - name: Generate Prisma Client
      run: |
        cd apps/api
        npm run prisma:generate
        cd ../..
    
    - name: ESLint
      run: npm run lint
    
    - name: TypeScript Check - API
      run: cd apps/api && npx tsc --noEmit
    
    - name: TypeScript Check - Web
      run: cd apps/web && npx tsc --noEmit
    
    - name: TypeScript Check - Worker
      run: cd apps/worker && npx tsc --noEmit
    
    - name: Build All Apps
      run: npm run build:all
    
    - name: Run Tests
      run: npm run test

  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Security Audit
      run: npm audit --audit-level=moderate
